### ISSUE TITLE
Fix MeshCentral top bar issue

### ISSUE THREAD

**Issue by DaanSelen** [DaanSelen/meshcentral-material#1]
Please refer to the image for further context.
![image](https://github.com/DaanSelen/meshcentral-material/assets/80752476/6a0576be-cb88-40b9-b320-c0defb160594)

The left menu bar is overlapping the MeshCentral text, I would like to have this resolved in a neat way but don't have the required front-end designing knowledge.

#How to reproduce?

To install MeshCentral following Official Documentation and after that drop the meshcentral-web folder into the root meshcentral folder.

**Comment by Zubykings** [comment]
So, i'm guessing your left-menu Navbar is set to fixed and the top set to 0, that is why it overlaps your top bar.

to solve this, set the top of the left menu-bar to the same height of the top bar menu. e.g If the height of the top bar is set to 100px, set the top of the left menu also to 100px.

.top-bar {
position: fixed;
left: 0;
right: 0;
height: 100px;
}

left-menu-bar {
position: fixed;
top: 100px;
left: 0;
bottom: 0;
}

This should fix this.

**Comment by DaanSelen** [comment]
> So, i'm guessing your left-menu Navbar is set to fixed and the top set to 0, that is why it overlaps your top bar.
> 
> to solve this, set the top of the left menu-bar to the same height of the top bar menu. e.g If the height of the top bar is set to 100px, set the top of the left menu also to 100px.
> 
> .top-bar { position: fixed; left: 0; right: 0; height: 100px; }
> 
> left-menu-bar { position: fixed; top: 100px; left: 0; bottom: 0; }
> 
> This should fix this.

I am going to look into positioning, howevery it does not look like these bars are found in the styles.css folder. Could it be that this is missing from the current files because they are default MeshCentral UI files somewhere else?
![image](https://github.com/DaanSelen/meshcentral-material/assets/80752476/64fc5d06-8cc7-4b74-8b15-04d16d936f72)

This is the original UI and you can see the same text at the top.

**Comment by DaanSelen** [comment]
Fixed the issue with a margin of 80 pixels, commit: Fix 1
